### PR TITLE
📝 (README.md): remove trailing spaces and fix minor formatting issues

### PR DESCRIPTION
**Pull request by PMassicotte**
Just fixing a little typo (`requests -> request`).

### CODE REVIEW

**Comment by dgkf** [comment]
Thanks for taking the time to take a look and make the correction.

I ended up re-writing all the instructions over in [SETUP.md](https://github.com/dgkf/debugadapter/blob/main/SETUP.md#configure)

I had to spend some time today getting an up-to-date `neovim` install setup and in the process learned that `nvim-dap` has evolved quite a bit since I last used it. I provided new instructions that are largely inspired by the recommended config for `python`. 

This worked for me, but please feel free to report issues as you encounter them. Don't expect anything to be too useful just yet, but hopefully I can get some breakpoints working _soon_.

**Comment by PMassicotte** [comment]
oh I am checking this right now!

**Comment by PMassicotte** [comment]
I built the dev version of R sucesfully, but my neovim install relies on `nvimcom` which now can not be build:

```
make[1]: Entering directory '/tmp/RtmpfUnwKa/R.INSTALL1cbed759d7a3f/nvimcom/src/apps'cc -pthread -std=gnu99 -O2 -Wall complete.c data_structures.c logging.c rnvimserver.c obbr.c tcp.c utilities.c ../common.c -o r
nvimserver                                                                                                                                                                                                          
gcc -shared -L/usr/local/lib -o nvimcom.so common.o nvimcom.o rd2md.o                                                                                                                                               
make[1]: Leaving directory '/tmp/RtmpfUnwKa/R.INSTALL1cbed759d7a3f/nvimcom/src/apps'                                                                                                                                
Error: package or namespace load failed for ‘nvimcom’: .onLoad failed in loadNamespace() for 'nvimcom', details:  call: dyn.load(file, DLLpath = DLLpath, ...)  error: unable to load shared object '/home/filoche/R
/x86_64-pc-linux-gnu-library/4.5/00LOCK-nvimcom/00new/nvimcom/libs/nvimcom.so':  /home/filoche/R/x86_64-pc-linux-gnu-library/4.5/00LOCK-nvimcom/00new/nvimcom/libs/nvimcom.so: undefined symbol: Rf_removeTaskCallba
ckByNameError: loading failedExecution halted   
```

Looks like some symbols are missing. Should I provide come additional flag when building R?

**Comment by dgkf** [comment]
Hmm - This is definitely beyond my familiarity. I was able to build this package in R-devel using:

```r
pak::pak("github::R-nvim/R.nvim/nvimcom")
```

No issues at all. 

You may consider setting up an isolated package library just for the devel version to avoid mixing packages compiled in each version. 

And please report back if you discover new steps using `R.nvim`! I don't have experience using it myself, but I think it's quite popular. And also, just to temper your expectations - currently this project will only get you as far as forming a connection between the IDE and DAP server, so it's not useful by any stretch of the imagination. If you do manage to get it working, your testing and feedback would be greatly appreciated, but if you don't you won't be missing out on much at this point.

**Comment by PMassicotte** [comment]
Thank you very much for your suggestion and your hard work on this package. Indeed you are right, I was able to install it using `pak`, but then when I try to `library(nvimcom)` I still get:

```
Error: package or namespace load failed for ‘nvimcom’:
 .onLoad failed in loadNamespace() for 'nvimcom', details:
  call: dyn.load(file, DLLpath = DLLpath, ...)
  error: unable to load shared object '/home/filoche/R/x86_64-pc-linux-gnu-library/4.5/nvimcom/libs/nvimcom.so':
  /home/filoche/R/x86_64-pc-linux-gnu-library/4.5/nvimcom/libs/nvimcom.so: undefined symbol: Rf_removeTaskCallbackByName
```

Also try to use `radian` and now getting:

```
Traceback (most recent call last):
  File "/home/filoche/.local/bin/radian", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/filoche/.local/lib/python3.12/site-packages/radian/app.py", line 121, in main
    RadianApplication(r_home, ver=__version__).run(options, cleanup=cleanup)
  File "/home/filoche/.local/lib/python3.12/site-packages/radian/app.py", line 218, in run
    rchitect.init(args=args, register_signal_handlers=True)
  File "/home/filoche/.local/lib/python3.12/site-packages/rchitect/setup.py", line 51, in init
    raise Exception(load_symbol_error())
Exception: Cannot load symbol MISSING: /usr/bin/R/lib/libR.so: undefined symbol: MISSING
```

Must be on my side on how I am building R. I will dig more tomorrow!

**Comment by dgkf** [comment]
It looks like that particular symbol used by `nvimcom` (`Rf_removeTaskCallbackByName`) was [recently "hidden"](https://github.com/wch/r-source/commit/00eb1f9a9faad244a76cd98ed05dc02c6452b5fa#diff-5ea4348bab8a5f5ce95785d05287a72869f48a3d364429b1580326b09f39da35R1689) in R's C API. I don't know the full details of what that means, but I think it means that package developers will have to be more explicit about which C headers they want to include and this one will not come by default. That probably means this won't work in its current state with `nvimcom` and `nvimcom` might need an update following the next version of R.

In `radian`, you might need to specify which version of R is being used by radian. The `R` executable in `/usr/bin/R` might not be the devel version that you're trying to use. 

You can use `R.version$status`, which should show `"Under development (unstable)"` if you're on `devel`

**Pull request closed without merging**
